server.port=8090

spring.datasource.url=jdbc:postgresql:store
#jdbc:postgresql://host:port/database
spring.datasource.username=spring-boot
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.postgresql.Driver

