server.port=8090

spring.datasource.url=jdbc:postgresql:store
#jdbc:postgresql://host:port/database
spring.datasource.username=spring-boot
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.postgresql.Driver

calc.prefix=P
calc.initial.value=0
output.file.path=../tomcat_data/simpleDao

spring.thymeleaf.check-template=false
