server.port=8090

spring.datasource.url=jdbc:postgresql:store
#jdbc:postgresql://host:port/database
spring.datasource.username=spring-boot
spring.datasource.password=qwerty
spring.datasource.driver-class-name=org.postgresql.Driver


logging.level.root=warn
logging.level.org.springframework=debug
logging.level.ru.inspired=debug
logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n